spring.application.name=マラソン日記
spring.datasource.url=jdbc:postgresql://localhost:5432/marathon
spring.datasource.username=marathon
spring.datasource.password=marathon
spring.datasource.driver-class-name=org.postgresql.Driver
